spring.application.name=livrariaUnipar

spring.datasource.url=jdbc:postgresql://localhost:5432/livraria
spring.datasource.username=postgres
spring.datasource.password=layssa
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG


